# Generated by Django 2.2 on 2019-04-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=50, verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=15, verbose_name='Metodo de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('id_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.Envio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.MetodoPago'),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.TipoPago'),
        ),
    ]
