# Generated by Django 2.2 on 2019-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, verbose_name='Codigo')),
            ],
        ),
    ]
