# Generated by Django 2.2 on 2019-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('nit', models.CharField(max_length=9, verbose_name='Nit')),
                ('email', models.EmailField(max_length=75, verbose_name='Correo Electronico')),
                ('tipo', models.CharField(choices=[('Min', 'Minorista'), ('May', 'Mayorista')], max_length=10, verbose_name='Tipo de Cliente')),
            ],
        ),
    ]
