# Generated by Django 2.2 on 2019-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(default='C/F', max_length=9, verbose_name='Nit'),
        ),
    ]
